### PR TITLE
fix!: knope, release, and publish

### LINKED ISSUE #31: `knope` doesn't list `Cargo.lock` in versioned files
The `knope.toml` file doesn't list the `Cargo.lock` as a versioned file, so it doesn't get updated with new releases.

### LINKED ISSUE #32: The CI job to publish `pyo3-opentelemetry` fails to detect `pyo3-opentelemetry-macros` is published
The CI job to release `pyo3-opentelemetry` tries to check if `pyo3-opentelemetry-macros` has been published to `crates.io`, but [recently the script just fails continuously](https://github.com/rigetti/pyo3-opentelemetry/actions/runs/21732983783/job/62783007604). It might be getting rate-limited, but it's not possible to tell currently. It should at least give some kind of visibility into failures, but ideally we'd find a more robust approach the publication.

### PR DESCRIPTION
**Pull request by asaites**
- Adds `Cargo.toml` to versioned files for crates.
- Updates the publish and release workflows.
- Uses `cargo publish --dry-run` to test whether `opentelemetry` can be published. See #32 for more details.

This is marked a breaking change to ensure the versions are updated with the correct `Cargo.lock` file.

Closes: #31
Closes: #32

### CODE REVIEW

File: scripts/ci/assert-macros-crate-published.sh [hunk 1]
```diff
@@ -4,19 +4,14 @@
...
-CRATE_ID=pyo3-opentelemetry-macros
-VERSION=$(yq -r -oj .package.version Cargo.toml)
-
-VERSION_DATA=$(curl -sSL https://crates.io/api/v1/crates/${CRATE_ID}/${VERSION} | yq -p json .version)
-
-if [ "${VERSION_DATA}" == "null" ]; then
-  echo "Version ${VERSION} not yet published"
-  exit 1
-else
+if cargo publish --dry-run -p "$CRATE" 2>&1 | tee /dev/stderr \
```
Comment (jselig-rigetti) [inline scripts/ci/assert-macros-crate-published.sh]: Nit - if this takes a while, could potentially run instead
 
```sh
cargo info $(cargo pkgid | cut -d "#" -f2)
```

**Review by jselig-rigetti — APPROVED** [review]
These changes are super clean 🙌

File: scripts/ci/assert-macros-crate-published.sh (hunk 1 above)
Comment (asaites) [reply scripts/ci/assert-macros-crate-published.sh]: That's a good idea, but it seems that if the package is part of the current workspace, `cargo info` pulls the information from the local `Cargo.toml`. We could do it by moving to a different directory outside of the workspace, but I think we'd also need to move into the `opentelemetry-macros` directory to use `cargo pkgid` like that, so it seems like a lot of mucking about. It's true that `cargo publish --dry-run` takes a bit longer, but the script is meant to give time for the `-macros` crate to get indexed anyway, so I don't think it's much of an issue.
